export const SAVE_FILM_LIST = 'SAVE_FILM_LIST';
export const OPEN_MOVIE_PAGE = 'OPEN_MOVIE_PAGE';
export const UPDATE_SORT_OPTION = 'UPDATE_SORT_OPTION';
export const UPDATE_SEARCH_OPTION = 'UPDATE_SEARCH_OPTION';
export const UPDATE_SEARCH_VALUE = 'UPDATE_SEARCH_VALUE';
